# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'khanhvucenter1.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(958, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 881, 321))
        self.tabWidget.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.tabWidget.setObjectName("tabWidget")
        self.twTTHS = QtWidgets.QWidget()
        self.twTTHS.setObjectName("twTTHS")
        self.btnXNtwTTHS = QtWidgets.QPushButton(self.twTTHS)
        self.btnXNtwTTHS.setGeometry(QtCore.QRect(140, 256, 75, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnXNtwTTHS.sizePolicy().hasHeightForWidth())
        self.btnXNtwTTHS.setSizePolicy(sizePolicy)
        self.btnXNtwTTHS.setObjectName("btnXNtwTTHS")
        self.layoutWidget = QtWidgets.QWidget(self.twTTHS)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 0, 271, 251))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.leMHStwTTHS = QtWidgets.QLineEdit(self.layoutWidget)
        self.leMHStwTTHS.setObjectName("leMHStwTTHS")
        self.gridLayout.addWidget(self.leMHStwTTHS, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.leHTHStwTTHS = QtWidgets.QLineEdit(self.layoutWidget)
        self.leHTHStwTTHS.setObjectName("leHTHStwTTHS")
        self.gridLayout.addWidget(self.leHTHStwTTHS, 1, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 2, 0, 1, 1)
        self.leNSHStwTTHS = QtWidgets.QLineEdit(self.layoutWidget)
        self.leNSHStwTTHS.setObjectName("leNSHStwTTHS")
        self.gridLayout.addWidget(self.leNSHStwTTHS, 2, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 3, 0, 1, 1)
        self.leSDTHStwTTHS = QtWidgets.QLineEdit(self.layoutWidget)
        self.leSDTHStwTTHS.setObjectName("leSDTHStwTTHS")
        self.gridLayout.addWidget(self.leSDTHStwTTHS, 3, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.leNVHtwTTHS = QtWidgets.QLineEdit(self.layoutWidget)
        self.leNVHtwTTHS.setObjectName("leNVHtwTTHS")
        self.gridLayout.addWidget(self.leNVHtwTTHS, 4, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 5, 0, 1, 1)
        self.leLtwTTHS = QtWidgets.QLineEdit(self.layoutWidget)
        self.leLtwTTHS.setObjectName("leLtwTTHS")
        self.gridLayout.addWidget(self.leLtwTTHS, 5, 1, 1, 1)
        self.tabWidget.addTab(self.twTTHS, "")
        self.twDSGV = QtWidgets.QWidget()
        self.twDSGV.setObjectName("twDSGV")
        self.btnXNtwDSGV = QtWidgets.QPushButton(self.twDSGV)
        self.btnXNtwDSGV.setGeometry(QtCore.QRect(130, 110, 75, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnXNtwDSGV.sizePolicy().hasHeightForWidth())
        self.btnXNtwDSGV.setSizePolicy(sizePolicy)
        self.btnXNtwDSGV.setObjectName("btnXNtwDSGV")
        self.layoutWidget1 = QtWidgets.QWidget(self.twDSGV)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 0, 271, 91))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 1, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 0, 0, 1, 1)
        self.leMGVtwDSGV = QtWidgets.QLineEdit(self.layoutWidget1)
        self.leMGVtwDSGV.setObjectName("leMGVtwDSGV")
        self.gridLayout_2.addWidget(self.leMGVtwDSGV, 0, 1, 1, 1)
        self.leTGVtwDSGV = QtWidgets.QLineEdit(self.layoutWidget1)
        self.leTGVtwDSGV.setObjectName("leTGVtwDSGV")
        self.gridLayout_2.addWidget(self.leTGVtwDSGV, 1, 1, 1, 1)
        self.tabWidget.addTab(self.twDSGV, "")
        self.twDMMH = QtWidgets.QWidget()
        self.twDMMH.setObjectName("twDMMH")
        self.btnXNtwDMMH = QtWidgets.QPushButton(self.twDMMH)
        self.btnXNtwDMMH.setGeometry(QtCore.QRect(140, 140, 75, 23))
        self.btnXNtwDMMH.setObjectName("btnXNtwDMMH")
        self.layoutWidget2 = QtWidgets.QWidget(self.twDMMH)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 0, 271, 91))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_18 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_18.setObjectName("label_18")
        self.gridLayout_3.addWidget(self.label_18, 0, 0, 1, 1)
        self.leMMHtwDMMH = QtWidgets.QLineEdit(self.layoutWidget2)
        self.leMMHtwDMMH.setObjectName("leMMHtwDMMH")
        self.gridLayout_3.addWidget(self.leMMHtwDMMH, 0, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_17.setObjectName("label_17")
        self.gridLayout_3.addWidget(self.label_17, 1, 0, 1, 1)
        self.leTMHtwDMMH = QtWidgets.QLineEdit(self.layoutWidget2)
        self.leTMHtwDMMH.setObjectName("leTMHtwDMMH")
        self.gridLayout_3.addWidget(self.leTMHtwDMMH, 1, 1, 1, 1)
        self.tabWidget.addTab(self.twDMMH, "")
        self.twDSN = QtWidgets.QWidget()
        self.twDSN.setObjectName("twDSN")
        self.btnXNtwDSN = QtWidgets.QPushButton(self.twDSN)
        self.btnXNtwDSN.setGeometry(QtCore.QRect(130, 220, 75, 23))
        self.btnXNtwDSN.setObjectName("btnXNtwDSN")
        self.layoutWidget3 = QtWidgets.QWidget(self.twDSN)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 0, 271, 171))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.layoutWidget3)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_24 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_24.setObjectName("label_24")
        self.gridLayout_4.addWidget(self.label_24, 0, 0, 1, 1)
        self.leMNtwDSN = QtWidgets.QLineEdit(self.layoutWidget3)
        self.leMNtwDSN.setObjectName("leMNtwDSN")
        self.gridLayout_4.addWidget(self.leMNtwDSN, 0, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_23.setObjectName("label_23")
        self.gridLayout_4.addWidget(self.label_23, 1, 0, 1, 1)
        self.leTNtwDSN = QtWidgets.QLineEdit(self.layoutWidget3)
        self.leTNtwDSN.setObjectName("leTNtwDSN")
        self.gridLayout_4.addWidget(self.leTNtwDSN, 1, 1, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_25.setObjectName("label_25")
        self.gridLayout_4.addWidget(self.label_25, 2, 0, 1, 1)
        self.cbbMMHtwDSN = QtWidgets.QComboBox(self.layoutWidget3)
        self.cbbMMHtwDSN.setObjectName("cbbMMHtwDSN")
        self.gridLayout_4.addWidget(self.cbbMMHtwDSN, 2, 1, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_26.setObjectName("label_26")
        self.gridLayout_4.addWidget(self.label_26, 3, 0, 1, 1)
        self.cbbMGVtwDSN = QtWidgets.QComboBox(self.layoutWidget3)
        self.cbbMGVtwDSN.setObjectName("cbbMGVtwDSN")
        self.gridLayout_4.addWidget(self.cbbMGVtwDSN, 3, 1, 1, 1)
        self.lblTenGVtwDSN = QtWidgets.QLabel(self.twDSN)
        self.lblTenGVtwDSN.setGeometry(QtCore.QRect(80, 170, 201, 21))
        self.lblTenGVtwDSN.setAutoFillBackground(False)
        self.lblTenGVtwDSN.setFrameShape(QtWidgets.QFrame.Box)
        self.lblTenGVtwDSN.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lblTenGVtwDSN.setText("")
        self.lblTenGVtwDSN.setScaledContents(False)
        self.lblTenGVtwDSN.setObjectName("lblTenGVtwDSN")
        self.label_27 = QtWidgets.QLabel(self.twDSN)
        self.label_27.setGeometry(QtCore.QRect(10, 170, 71, 20))
        self.label_27.setObjectName("label_27")
        self.tabWidget.addTab(self.twDSN, "")
        self.twHSTN = QtWidgets.QWidget()
        self.twHSTN.setObjectName("twHSTN")
        self.btnXNtwHSTN = QtWidgets.QPushButton(self.twHSTN)
        self.btnXNtwHSTN.setGeometry(QtCore.QRect(160, 150, 75, 23))
        self.btnXNtwHSTN.setObjectName("btnXNtwHSTN")
        self.label_3 = QtWidgets.QLabel(self.twHSTN)
        self.label_3.setGeometry(QtCore.QRect(10, 100, 71, 21))
        self.label_3.setObjectName("label_3")
        self.lblTHStwHSTN = QtWidgets.QLabel(self.twHSTN)
        self.lblTHStwHSTN.setGeometry(QtCore.QRect(80, 100, 201, 21))
        self.lblTHStwHSTN.setFrameShape(QtWidgets.QFrame.Box)
        self.lblTHStwHSTN.setText("")
        self.lblTHStwHSTN.setObjectName("lblTHStwHSTN")
        self.layoutWidget4 = QtWidgets.QWidget(self.twHSTN)
        self.layoutWidget4.setGeometry(QtCore.QRect(10, 0, 271, 91))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.layoutWidget4)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_40 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_40.setObjectName("label_40")
        self.gridLayout_10.addWidget(self.label_40, 0, 0, 1, 1)
        self.cbbMNtwHSTN = QtWidgets.QComboBox(self.layoutWidget4)
        self.cbbMNtwHSTN.setObjectName("cbbMNtwHSTN")
        self.gridLayout_10.addWidget(self.cbbMNtwHSTN, 0, 1, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_39.setObjectName("label_39")
        self.gridLayout_10.addWidget(self.label_39, 1, 0, 1, 1)
        self.cbbMHStwHSTN = QtWidgets.QComboBox(self.layoutWidget4)
        self.cbbMHStwHSTN.setObjectName("cbbMHStwHSTN")
        self.gridLayout_10.addWidget(self.cbbMHStwHSTN, 1, 1, 1, 1)
        self.tabWidget.addTab(self.twHSTN, "")
        self.twTHP = QtWidgets.QWidget()
        self.twTHP.setObjectName("twTHP")
        self.btnXNtwTHP = QtWidgets.QPushButton(self.twTHP)
        self.btnXNtwTHP.setGeometry(QtCore.QRect(130, 190, 75, 23))
        self.btnXNtwTHP.setObjectName("btnXNtwTHP")
        self.lblTHStwTHP = QtWidgets.QLabel(self.twTHP)
        self.lblTHStwTHP.setGeometry(QtCore.QRect(290, 10, 191, 31))
        self.lblTHStwTHP.setFrameShape(QtWidgets.QFrame.Box)
        self.lblTHStwTHP.setText("")
        self.lblTHStwTHP.setObjectName("lblTHStwTHP")
        self.widget = QtWidgets.QWidget(self.twTHP)
        self.widget.setGeometry(QtCore.QRect(10, 0, 271, 91))
        self.widget.setObjectName("widget")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_42 = QtWidgets.QLabel(self.widget)
        self.label_42.setObjectName("label_42")
        self.gridLayout_6.addWidget(self.label_42, 0, 0, 1, 1)
        self.cbbMHStwTHP = QtWidgets.QComboBox(self.widget)
        self.cbbMHStwTHP.setObjectName("cbbMHStwTHP")
        self.gridLayout_6.addWidget(self.cbbMHStwTHP, 0, 1, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.widget)
        self.label_43.setObjectName("label_43")
        self.gridLayout_6.addWidget(self.label_43, 1, 0, 1, 1)
        self.leNTtwTHP = QtWidgets.QLineEdit(self.widget)
        self.leNTtwTHP.setObjectName("leNTtwTHP")
        self.gridLayout_6.addWidget(self.leNTtwTHP, 1, 1, 1, 1)
        self.tabWidget.addTab(self.twTHP, "")
        self.twDD = QtWidgets.QWidget()
        self.twDD.setObjectName("twDD")
        self.btnXNtwDD = QtWidgets.QPushButton(self.twDD)
        self.btnXNtwDD.setGeometry(QtCore.QRect(120, 200, 75, 23))
        self.btnXNtwDD.setObjectName("btnXNtwDD")
        self.layoutWidget5 = QtWidgets.QWidget(self.twDD)
        self.layoutWidget5.setGeometry(QtCore.QRect(10, 0, 271, 171))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.layoutWidget5)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_47 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_47.setObjectName("label_47")
        self.gridLayout_5.addWidget(self.label_47, 0, 0, 1, 1)
        self.cbbMMHStwDD = QtWidgets.QComboBox(self.layoutWidget5)
        self.cbbMMHStwDD.setObjectName("cbbMMHStwDD")
        self.gridLayout_5.addWidget(self.cbbMMHStwDD, 0, 1, 1, 1)
        self.label_46 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_46.setObjectName("label_46")
        self.gridLayout_5.addWidget(self.label_46, 1, 0, 1, 1)
        self.cbbMNtwDD = QtWidgets.QComboBox(self.layoutWidget5)
        self.cbbMNtwDD.setObjectName("cbbMNtwDD")
        self.gridLayout_5.addWidget(self.cbbMNtwDD, 1, 1, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_45.setObjectName("label_45")
        self.gridLayout_5.addWidget(self.label_45, 2, 0, 1, 1)
        self.cbbMHStwDD = QtWidgets.QComboBox(self.layoutWidget5)
        self.cbbMHStwDD.setObjectName("cbbMHStwDD")
        self.gridLayout_5.addWidget(self.cbbMHStwDD, 2, 1, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_44.setObjectName("label_44")
        self.gridLayout_5.addWidget(self.label_44, 3, 0, 1, 1)
        self.leNGHtwDD = QtWidgets.QLineEdit(self.layoutWidget5)
        self.leNGHtwDD.setObjectName("leNGHtwDD")
        self.gridLayout_5.addWidget(self.leNGHtwDD, 3, 1, 1, 1)
        self.tabWidget.addTab(self.twDD, "")
        self.twHP = QtWidgets.QWidget()
        self.twHP.setObjectName("twHP")
        self.btnXNtwHP = QtWidgets.QPushButton(self.twHP)
        self.btnXNtwHP.setGeometry(QtCore.QRect(150, 230, 75, 23))
        self.btnXNtwHP.setObjectName("btnXNtwHP")
        self.layoutWidget6 = QtWidgets.QWidget(self.twHP)
        self.layoutWidget6.setGeometry(QtCore.QRect(10, 0, 271, 171))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.layoutWidget6)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget6)
        self.label_4.setObjectName("label_4")
        self.gridLayout_9.addWidget(self.label_4, 0, 0, 1, 1)
        self.cbbMHStwHP = QtWidgets.QComboBox(self.layoutWidget6)
        self.cbbMHStwHP.setObjectName("cbbMHStwHP")
        self.gridLayout_9.addWidget(self.cbbMHStwHP, 0, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget6)
        self.label_11.setObjectName("label_11")
        self.gridLayout_9.addWidget(self.label_11, 1, 0, 1, 1)
        self.cbbMMHtwHP = QtWidgets.QComboBox(self.layoutWidget6)
        self.cbbMMHtwHP.setObjectName("cbbMMHtwHP")
        self.gridLayout_9.addWidget(self.cbbMMHtwHP, 1, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget6)
        self.label_12.setObjectName("label_12")
        self.gridLayout_9.addWidget(self.label_12, 2, 0, 1, 1)
        self.cbbMGVtwHP = QtWidgets.QComboBox(self.layoutWidget6)
        self.cbbMGVtwHP.setObjectName("cbbMGVtwHP")
        self.gridLayout_9.addWidget(self.cbbMGVtwHP, 2, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.layoutWidget6)
        self.label_13.setObjectName("label_13")
        self.gridLayout_9.addWidget(self.label_13, 3, 0, 1, 1)
        self.leHPtwHP = QtWidgets.QLineEdit(self.layoutWidget6)
        self.leHPtwHP.setObjectName("leHPtwHP")
        self.gridLayout_9.addWidget(self.leHPtwHP, 3, 1, 1, 1)
        self.tabWidget.addTab(self.twHP, "")
        self.twPC = QtWidgets.QWidget()
        self.twPC.setObjectName("twPC")
        self.btnXNtwPCGD = QtWidgets.QPushButton(self.twPC)
        self.btnXNtwPCGD.setGeometry(QtCore.QRect(180, 130, 75, 23))
        self.btnXNtwPCGD.setObjectName("btnXNtwPCGD")
        self.layoutWidget7 = QtWidgets.QWidget(self.twPC)
        self.layoutWidget7.setGeometry(QtCore.QRect(10, 0, 271, 91))
        self.layoutWidget7.setObjectName("layoutWidget7")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.layoutWidget7)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_14 = QtWidgets.QLabel(self.layoutWidget7)
        self.label_14.setObjectName("label_14")
        self.gridLayout_7.addWidget(self.label_14, 0, 0, 1, 1)
        self.cbbMGVtwPCGD = QtWidgets.QComboBox(self.layoutWidget7)
        self.cbbMGVtwPCGD.setObjectName("cbbMGVtwPCGD")
        self.gridLayout_7.addWidget(self.cbbMGVtwPCGD, 0, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.layoutWidget7)
        self.label_15.setObjectName("label_15")
        self.gridLayout_7.addWidget(self.label_15, 1, 0, 1, 1)
        self.cbbMMHtwPCGD = QtWidgets.QComboBox(self.layoutWidget7)
        self.cbbMMHtwPCGD.setObjectName("cbbMMHtwPCGD")
        self.gridLayout_7.addWidget(self.cbbMMHtwPCGD, 1, 1, 1, 1)
        self.tabWidget.addTab(self.twPC, "")
        self.twTKB = QtWidgets.QWidget()
        self.twTKB.setObjectName("twTKB")
        self.layoutWidget8 = QtWidgets.QWidget(self.twTKB)
        self.layoutWidget8.setGeometry(QtCore.QRect(10, 0, 271, 91))
        self.layoutWidget8.setObjectName("layoutWidget8")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.layoutWidget8)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_19 = QtWidgets.QLabel(self.layoutWidget8)
        self.label_19.setObjectName("label_19")
        self.gridLayout_8.addWidget(self.label_19, 0, 0, 1, 1)
        self.cbbMNtwTKB = QtWidgets.QComboBox(self.layoutWidget8)
        self.cbbMNtwTKB.setObjectName("cbbMNtwTKB")
        self.gridLayout_8.addWidget(self.cbbMNtwTKB, 0, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.layoutWidget8)
        self.label_16.setObjectName("label_16")
        self.gridLayout_8.addWidget(self.label_16, 1, 0, 1, 1)
        self.cbbNGHtwTKB = QtWidgets.QComboBox(self.layoutWidget8)
        self.cbbNGHtwTKB.setObjectName("cbbNGHtwTKB")
        self.gridLayout_8.addWidget(self.cbbNGHtwTKB, 1, 1, 1, 1)
        self.btnXNtwTKB = QtWidgets.QPushButton(self.twTKB)
        self.btnXNtwTKB.setGeometry(QtCore.QRect(180, 130, 75, 23))
        self.btnXNtwTKB.setObjectName("btnXNtwTKB")
        self.tabWidget.addTab(self.twTKB, "")
        self.twTTCN = QtWidgets.QWidget()
        self.twTTCN.setObjectName("twTTCN")
        self.btnXNtwTTCN = QtWidgets.QPushButton(self.twTTCN)
        self.btnXNtwTTCN.setGeometry(QtCore.QRect(160, 210, 75, 23))
        self.btnXNtwTTCN.setObjectName("btnXNtwTTCN")
        self.widget1 = QtWidgets.QWidget(self.twTTCN)
        self.widget1.setGeometry(QtCore.QRect(10, 0, 271, 171))
        self.widget1.setObjectName("widget1")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.widget1)
        self.gridLayout_12.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.label_20 = QtWidgets.QLabel(self.widget1)
        self.label_20.setObjectName("label_20")
        self.gridLayout_12.addWidget(self.label_20, 0, 0, 1, 1)
        self.cbbMHStwTTCN = QtWidgets.QComboBox(self.widget1)
        self.cbbMHStwTTCN.setObjectName("cbbMHStwTTCN")
        self.gridLayout_12.addWidget(self.cbbMHStwTTCN, 0, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.widget1)
        self.label_21.setObjectName("label_21")
        self.gridLayout_12.addWidget(self.label_21, 1, 0, 1, 1)
        self.leNNtwTTCN = QtWidgets.QLineEdit(self.widget1)
        self.leNNtwTTCN.setObjectName("leNNtwTTCN")
        self.gridLayout_12.addWidget(self.leNNtwTTCN, 1, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.widget1)
        self.label_22.setObjectName("label_22")
        self.gridLayout_12.addWidget(self.label_22, 2, 0, 1, 1)
        self.leTDBHtwTTCN = QtWidgets.QLineEdit(self.widget1)
        self.leTDBHtwTTCN.setObjectName("leTDBHtwTTCN")
        self.gridLayout_12.addWidget(self.leTDBHtwTTCN, 2, 1, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.widget1)
        self.label_28.setObjectName("label_28")
        self.gridLayout_12.addWidget(self.label_28, 3, 0, 1, 1)
        self.leNDGCtwTTCN = QtWidgets.QLineEdit(self.widget1)
        self.leNDGCtwTTCN.setObjectName("leNDGCtwTTCN")
        self.gridLayout_12.addWidget(self.leNDGCtwTTCN, 3, 1, 1, 1)
        self.tabWidget.addTab(self.twTTCN, "")
        self.twTTN = QtWidgets.QWidget()
        self.twTTN.setObjectName("twTTN")
        self.btnXNtwTTN = QtWidgets.QPushButton(self.twTTN)
        self.btnXNtwTTN.setGeometry(QtCore.QRect(140, 200, 75, 23))
        self.btnXNtwTTN.setObjectName("btnXNtwTTN")
        self.widget2 = QtWidgets.QWidget(self.twTTN)
        self.widget2.setGeometry(QtCore.QRect(10, 0, 271, 131))
        self.widget2.setObjectName("widget2")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.widget2)
        self.gridLayout_11.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_29 = QtWidgets.QLabel(self.widget2)
        self.label_29.setObjectName("label_29")
        self.gridLayout_11.addWidget(self.label_29, 0, 0, 1, 1)
        self.cbbMNtwTTN = QtWidgets.QComboBox(self.widget2)
        self.cbbMNtwTTN.setObjectName("cbbMNtwTTN")
        self.gridLayout_11.addWidget(self.cbbMNtwTTN, 0, 1, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.widget2)
        self.label_30.setObjectName("label_30")
        self.gridLayout_11.addWidget(self.label_30, 1, 0, 1, 1)
        self.leTDBHtwTTN = QtWidgets.QLineEdit(self.widget2)
        self.leTDBHtwTTN.setObjectName("leTDBHtwTTN")
        self.gridLayout_11.addWidget(self.leTDBHtwTTN, 1, 1, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.widget2)
        self.label_31.setObjectName("label_31")
        self.gridLayout_11.addWidget(self.label_31, 2, 0, 1, 1)
        self.leTHNtwTTN_2 = QtWidgets.QLineEdit(self.widget2)
        self.leTHNtwTTN_2.setObjectName("leTHNtwTTN_2")
        self.gridLayout_11.addWidget(self.leTHNtwTTN_2, 2, 1, 1, 1)
        self.tabWidget.addTab(self.twTTN, "")
        self.btnshow = QtWidgets.QPushButton(self.centralwidget)
        self.btnshow.setGeometry(QtCore.QRect(270, 420, 75, 23))
        self.btnshow.setObjectName("btnshow")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 958, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(5)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnXNtwTTHS.setText(_translate("MainWindow", "Xác nhận"))
        self.label.setText(_translate("MainWindow", "Mã học sinh:"))
        self.label_2.setText(_translate("MainWindow", "Họ tên học sinh:"))
        self.label_10.setText(_translate("MainWindow", "Năm sinh"))
        self.label_7.setText(_translate("MainWindow", "SDT học sinh:"))
        self.label_5.setText(_translate("MainWindow", "Ngày vào học:"))
        self.label_6.setText(_translate("MainWindow", "Lớp :"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.twTTHS), _translate("MainWindow", "DSHS"))
        self.btnXNtwDSGV.setText(_translate("MainWindow", "Xác nhận"))
        self.label_8.setText(_translate("MainWindow", "Tên giáo viên"))
        self.label_9.setText(_translate("MainWindow", "Mã giáo viên"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.twDSGV), _translate("MainWindow", "DSGV"))
        self.btnXNtwDMMH.setText(_translate("MainWindow", "Xác nhận"))
        self.label_18.setText(_translate("MainWindow", "Mã môn học"))
        self.label_17.setText(_translate("MainWindow", "Tên môn học"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.twDMMH), _translate("MainWindow", "DMMH"))
        self.btnXNtwDSN.setText(_translate("MainWindow", "Xác nhận"))
        self.label_24.setText(_translate("MainWindow", "Mã nhóm"))
        self.label_23.setText(_translate("MainWindow", "Tên nhóm"))
        self.label_25.setText(_translate("MainWindow", "Mã môn học"))
        self.label_26.setText(_translate("MainWindow", "Mã giáo viên"))
        self.label_27.setText(_translate("MainWindow", "Tên giáo viên"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.twDSN), _translate("MainWindow", "DSN"))
        self.btnXNtwHSTN.setText(_translate("MainWindow", "Xác nhận"))
        self.label_3.setText(_translate("MainWindow", "Tên học sinh"))
        self.label_40.setText(_translate("MainWindow", "Mã nhóm"))
        self.label_39.setText(_translate("MainWindow", "Mã học sinh"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.twHSTN), _translate("MainWindow", "HSTN"))
        self.btnXNtwTHP.setText(_translate("MainWindow", "Xác nhận"))
        self.label_42.setText(_translate("MainWindow", "Mã học sinh"))
        self.label_43.setText(_translate("MainWindow", "Ngày thu"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.twTHP), _translate("MainWindow", "THP"))
        self.btnXNtwDD.setText(_translate("MainWindow", "Xác nhận"))
        self.label_47.setText(_translate("MainWindow", "Mã môn học"))
        self.label_46.setText(_translate("MainWindow", "Mã nhóm"))
        self.label_45.setText(_translate("MainWindow", "Mã học sinh"))
        self.label_44.setText(_translate("MainWindow", "Ngày giờ học"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.twDD), _translate("MainWindow", "Điểm danh"))
        self.btnXNtwHP.setText(_translate("MainWindow", "Xác nhận"))
        self.label_4.setText(_translate("MainWindow", "Mã học sinh"))
        self.label_11.setText(_translate("MainWindow", "Mã môn học"))
        self.label_12.setText(_translate("MainWindow", "Mã giáo viên"))
        self.label_13.setText(_translate("MainWindow", "Học phí"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.twHP), _translate("MainWindow", "Học phí"))
        self.btnXNtwPCGD.setText(_translate("MainWindow", "Xác nhận"))
        self.label_14.setText(_translate("MainWindow", "Mã giáo viên"))
        self.label_15.setText(_translate("MainWindow", "Mã môn học"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.twPC), _translate("MainWindow", "PCGD"))
        self.label_19.setText(_translate("MainWindow", "Mã nhóm"))
        self.label_16.setText(_translate("MainWindow", "Ngày giờ học"))
        self.btnXNtwTKB.setText(_translate("MainWindow", "Xác nhận"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.twTKB), _translate("MainWindow", "TKB"))
        self.btnXNtwTTCN.setText(_translate("MainWindow", "Xác nhận"))
        self.label_20.setText(_translate("MainWindow", "Mã học sinh"))
        self.label_21.setText(_translate("MainWindow", "Ngày Note"))
        self.label_22.setText(_translate("MainWindow", "Tiêu đề bài học"))
        self.label_28.setText(_translate("MainWindow", "Nội dung ghi chú"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.twTTCN), _translate("MainWindow", "TTCN"))
        self.btnXNtwTTN.setText(_translate("MainWindow", "Xác nhận"))
        self.label_29.setText(_translate("MainWindow", "Mã nhóm"))
        self.label_30.setText(_translate("MainWindow", "Tiêu đề bài học"))
        self.label_31.setText(_translate("MainWindow", "Tình hình nhóm"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.twTTN), _translate("MainWindow", "TTN"))
        self.btnshow.setText(_translate("MainWindow", "show data"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
