# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TestUIDesign.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FindReplace(object):
    def setupUi(self, FindReplace):
        FindReplace.setObjectName("FindReplace")
        FindReplace.resize(381, 207)
        self.layoutWidget = QtWidgets.QWidget(FindReplace)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 10, 346, 182))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.findwhat = QtWidgets.QLineEdit(self.layoutWidget)
        self.findwhat.setObjectName("findwhat")
        self.horizontalLayout_3.addWidget(self.findwhat)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.replacewhat = QtWidgets.QLineEdit(self.layoutWidget)
        self.replacewhat.setObjectName("replacewhat")
        self.horizontalLayout_4.addWidget(self.replacewhat)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.casecheckbox = QtWidgets.QCheckBox(self.layoutWidget)
        self.casecheckbox.setObjectName("casecheckbox")
        self.horizontalLayout.addWidget(self.casecheckbox)
        self.wholecheckbox = QtWidgets.QCheckBox(self.layoutWidget)
        self.wholecheckbox.setChecked(True)
        self.wholecheckbox.setObjectName("wholecheckbox")
        self.horizontalLayout.addWidget(self.wholecheckbox)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.syntaxcombobox = QtWidgets.QComboBox(self.layoutWidget)
        self.syntaxcombobox.setObjectName("syntaxcombobox")
        self.syntaxcombobox.addItem("")
        self.syntaxcombobox.addItem("")
        self.horizontalLayout_2.addWidget(self.syntaxcombobox)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(20, 28, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout_5.addLayout(self.verticalLayout_3)
        self.line = QtWidgets.QFrame(self.layoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_5.addWidget(self.line)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.findbutton = QtWidgets.QPushButton(self.layoutWidget)
        self.findbutton.setObjectName("findbutton")
        self.verticalLayout_2.addWidget(self.findbutton)
        self.replacebutton = QtWidgets.QPushButton(self.layoutWidget)
        self.replacebutton.setObjectName("replacebutton")
        self.verticalLayout_2.addWidget(self.replacebutton)
        self.repallbut = QtWidgets.QPushButton(self.layoutWidget)
        self.repallbut.setObjectName("repallbut")
        self.verticalLayout_2.addWidget(self.repallbut)
        spacerItem1 = QtWidgets.QSpacerItem(20, 38, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.closebut = QtWidgets.QPushButton(self.layoutWidget)
        self.closebut.setObjectName("closebut")
        self.verticalLayout_2.addWidget(self.closebut)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        self.label.setBuddy(self.findwhat)
        self.label_2.setBuddy(self.replacewhat)
        self.label_3.setBuddy(self.syntaxcombobox)

        self.retranslateUi(FindReplace)
        self.closebut.clicked.connect(FindReplace.reject)
        QtCore.QMetaObject.connectSlotsByName(FindReplace)
        FindReplace.setTabOrder(self.findwhat, self.replacewhat)
        FindReplace.setTabOrder(self.replacewhat, self.casecheckbox)
        FindReplace.setTabOrder(self.casecheckbox, self.wholecheckbox)
        FindReplace.setTabOrder(self.wholecheckbox, self.syntaxcombobox)
        FindReplace.setTabOrder(self.syntaxcombobox, self.findbutton)
        FindReplace.setTabOrder(self.findbutton, self.replacebutton)
        FindReplace.setTabOrder(self.replacebutton, self.repallbut)
        FindReplace.setTabOrder(self.repallbut, self.closebut)

    def retranslateUi(self, FindReplace):
        _translate = QtCore.QCoreApplication.translate
        FindReplace.setWindowTitle(_translate("FindReplace", "Dialog"))
        self.label.setText(_translate("FindReplace", "Find &What"))
        self.label_2.setText(_translate("FindReplace", "Replace w&ith"))
        self.casecheckbox.setText(_translate("FindReplace", "&Case sensitive"))
        self.wholecheckbox.setText(_translate("FindReplace", "Wh&ole words"))
        self.label_3.setText(_translate("FindReplace", "&Syntax"))
        self.syntaxcombobox.setItemText(0, _translate("FindReplace", "Literal Text"))
        self.syntaxcombobox.setItemText(1, _translate("FindReplace", "Regular Expression"))
        self.findbutton.setText(_translate("FindReplace", "&Find"))
        self.replacebutton.setText(_translate("FindReplace", "&Replace"))
        self.repallbut.setText(_translate("FindReplace", "Replace &All"))
        self.closebut.setText(_translate("FindReplace", "&Close"))
